### ISSUE TITLE
克隆项目无法跑起，是否提供初始化sql

### ISSUE THREAD

**Issue by guangzhonghedd01** [zhangfangsong/Lara#2]
## 步骤
* php artisan migrate
* 有没初始化数据库

**Comment by guangzhonghedd01** [comment]
# php artisan migrate:status
+------+-------------------------------------------------------+
| Ran? | Migration                                             |
+------+-------------------------------------------------------+
| Y    | 2014_10_12_000000_create_users_table                  |
| Y    | 2018_05_11_024840_create_categories_table             |
| Y    | 2018_05_11_040613_add_description_to_categories_table |
| Y    | 2018_05_12_155005_create_tags_table                   |
| Y    | 2018_05_13_052846_create_links_table                  |
| Y    | 2018_05_14_064021_create_pages_table                  |
| Y    | 2018_05_15_023756_create_articles_table               |
| Y    | 2018_05_23_020340_add_description_to_users_table      |
| Y    | 2018_05_23_060750_create_configs_table                |
| Y    | 2018_05_24_055750_add_status_to_users_table           |
| Y    | 2018_05_24_113322_create_comments_table               |
| Y    | 2018_05_25_082819_create_roles_table                  |
| Y    | 2018_05_28_015833_add_url_to_categories_table         |
| Y    | 2018_05_28_081109_change_value_field_to_configs       |
| Y    | 2018_06_13_035033_create_collections_table            |
| Y    | 2018_07_15_032530_create_nodes_table                  |
| Y    | 2018_07_15_034451_create_node_role_table              |
| Y    | 2018_07_15_063249_add_alias_to_nodes_table            |
| Y    | 2018_08_19_044139_change_role_id_to_users_table       |
+------+-------------------------------------------------------+

**Comment by zhangfangsong** [comment]
php artisan db:seed 填充数据，这里是安装步骤：http://www.zfsphp.com/41.html @guangzhonghedd01
